### ISSUE TITLE
Compatibility with Builder 3.0?

### ISSUE THREAD

**Issue by dazoakley** [dazoakley/biomart#14]
I love your Biomart gem. It's integral to one of my projects.

I notice you updated it to deal with a new version of builder. Unfortunately, I'm still getting a bug with builder-3.0.0, which is required by the version of rails I'm using.

```
>> celegans.search(:filters => {"wormbase_locus" => "Y110A7A.14"})
ArgumentError: wrong number of arguments (1 for 0)
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlbase.rb:135:in `to_xs'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlbase.rb:135:in `_escape'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlbase.rb:140:in `_escape_quote'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:320:in `_attr_value'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:308:in `_insert_attributes'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:306:in `each'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:306:in `_insert_attributes'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:284:in `_special'
    from /usr/lib/ruby/gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb:250:in `instruct!'
    from /usr/lib/ruby/gems/1.8/gems/biomart-0.2.2/lib/biomart/dataset.rb:180:in `generate_xml'
    from /usr/lib/ruby/gems/1.8/gems/biomart-0.2.2/lib/biomart/dataset.rb:163:in `search'
    from (irb):8
```

You can reproduce this with any call to search().

Any thoughts on how I might circumvent this?

**Comment by dazoakley** [comment]
More info...

```
Daz,

It's Ruby 1.8.7. Here are steps to reproduce in script/rails console (it's edge rails).

>> biomart = Biomart::Server.new( "http://www.biomart.org/biomart" )
>> ce = biomart.datasets["celegans_gene_ensembl"]
>> ce.search(:attributes => ["wormbase_locus", "entrezgene"]) # error

Apologies for taking so long -- was out of town all weekend. Thanks for having a look.
```

**Comment by dazoakley** [comment]
Right...  Testing with irb on ruby-1.8.7-p334 is fine:

```
[ do2@guest-193-062-206-044 ~ ] irb
ruby-1.8.7-p334 :001 > require 'biomart'
 => true 
ruby-1.8.7-p334 :002 > biomart = Biomart::Server.new( "http://www.biomart.org/biomart" )
 => #<Biomart::Server:0x10139a7e0 @datasets={}, @databases={}, @url="http://www.biomart.org/biomart/martservice"> 
ruby-1.8.7-p334 :003 > ce = biomart.datasets["celegans_gene_ensembl"]
 => #<Biomart::Dataset:0x101bb5678 @importables={}, @display_name="Caenorhabditis elegans genes (WS220)", @filters={}, @attributes={}, @exportables={}, @url="http://www.biomart.org/biomart/martservice", @name="celegans_gene_ensembl", @visible=true> 
ruby-1.8.7-p334 :004 > res = ce.search(:attributes => ["wormbase_locus", "entrezgene"]); true
 => true 
ruby-1.8.7-p334 :005 >
```

Looks like it's something in edge rails?  Will checkout and have a play...

**Comment by dazoakley** [comment]
And here's the output from the rails console using edge rails (3.1.0.beta):

```

Loading development environment (Rails 3.1.0.beta)
ruby-1.8.7-p334 :001 > biomart = Biomart::Server.new( "http://www.biomart.org/biomart" )
 => #<Biomart::Server:0x102f052a0 @datasets={}, @databases={}, @url="http://www.biomart.org/biomart/martservice"> 
ruby-1.8.7-p334 :002 > ce = biomart.datasets["celegans_gene_ensembl"]
 => #<Biomart::Dataset:0x1033911c0 @attributes={}, @visible=true, @importables={}, @display_name="Caenorhabditis elegans genes (WS220)", @filters={}, @url="http://www.biomart.org/biomart/martservice", @name="celegans_gene_ensembl", @exportables={}> 
ruby-1.8.7-p334 :003 > res = ce.search(:attributes => ["wormbase_locus", "entrezgene"]); true
 => true 
ruby-1.8.7-p334 :004 > res.keys
 => [:data, :headers] 
ruby-1.8.7-p334 :007 > res[:headers]
 => ["wormbase_locus", "entrezgene"] 
ruby-1.8.7-p334 :008 > res[:data].size
 => 22105 
ruby-1.8.7-p334 :009 > 
```

**Comment by dazoakley** [comment]
Unable to replicate problem.  Issue closed.
